const { v4: uuidv4 } = require("uuid");

let posts = [
  {
    id: uuidv4(),
    username: "omraja451",
    likes: 14,
    comments: [
      "wow",
      "nice",
      "nice pic",
      "looking handsome",
      "beautiful",
      "I've never seen something like this in my life.",
      "jo like nahi karega exam me fail ho jayega",
      "ye comment padhne wale ke maa baap hamesha khush rahe",
    ],
    shares: 12,
    src:"pic1.jpg",
    caption: "I love nature 🌳",
  },
  {
    id: uuidv4(),
    username: "arjun_kumar",
    likes: 25,
    comments: [
      "amazing view!",
      "nature lover ❤️",
      "so peaceful",
      "wow, great shot!",
      "beautiful click",
      "reminds me of my last trip",
      "jo like karega wo hamesha khush rahega",
      "kamal ki photo hai",
    ],
    shares: 18,
    src: "pic2.jpg",
    caption: "Sunset vibes 🌄",
  },
  {
    id: uuidv4(),
    username: "priya_sharma",
    likes: 34,
    comments: [
      "so aesthetic!",
      "loving the vibes",
      "looks serene",
      "where is this place?",
      "amazing photography",
      "like kar diya, ab exam me full marks",
      "kitni cool pic hai!",
      "dream destination 🏞️",
    ],
    shares: 25,
    src: "pic3.jpg",
    caption: "Misty mornings 🌲",
  },
  {
    id: uuidv4(),
    username: "rahul_gupta",
    likes: 19,
    comments: [
      "kya baat hai!",
      "majestic view 👌",
      "nature's beauty",
      "jo like nahi karega uska breakup ho jayega 😂",
      "click kaha ki hai?",
      "mind refreshing pic",
      "awesome vibes ❤️",
      "pure magic!",
    ],
    shares: 14,
    src: "pic4.jpg",
    caption: "Blue serenity 💙",
  },
  {
    id: uuidv4(),
    username: "anita_patel",
    likes: 28,
    comments: [
      "simply wow",
      "feeling relaxed seeing this",
      "nature therapy 🌿",
      "divine pic!",
      "bahut sahi click",
      "jo share karega wo millionaire banega",
      "full positive vibes",
      "love this",
    ],
    shares: 20,
    src: "pic5.jpg",
    caption: "Walking through greens 🌳🌿",
  },
  {
    id: uuidv4(),
    username: "vicky_malhotra",
    likes: 31,
    comments: [
      "heaven on earth",
      "natural beauty 😍",
      "simply awesome!",
      "green therapy 🌱",
      "photo dekh ke chain mila",
      "beyond words",
      "ab like kar diya!",
      "best shot ever!",
    ],
    shares: 15,
    src: "pic6.jpg",
    caption: "Golden riverside 🌅",
  },
  {
    id: uuidv4(),
    username: "neha_mehra",
    likes: 45,
    comments: [
      "peaceful scene",
      "kitni sukoon wali jagah",
      "sahi click hai!",
      "majestic and magical",
      "perfectly clicked",
      "my dream place",
      "like kar diya! 🌈",
      "so lovely",
    ],
    shares: 30,
    src: "pic7.jpg",
    caption: "Reflections of peace 🌊",
  },
  {
    id: uuidv4(),
    username: "rohit_khanna",
    likes: 22,
    comments: [
      "kya baat hai 👏",
      "so soothing",
      "love this pic",
      "stunning view",
      "such raw beauty!",
      "ye pic sabse best hai",
      "full like and share",
      "nature ka asli rang",
    ],
    shares: 17,
    src: "pic8.jpg",
    caption: "Snowy dreams ❄️",
  },
  {
    id: uuidv4(),
    username: "ankit_dubey",
    likes: 26,
    comments: [
      "bahut sahi jagah hai!",
      "dream location ❤️",
      "kitna sukoon hai",
      "divine click",
      "awesome picture!",
      "aaj tak nahi dekha kuch aisa",
      "just breathtaking!",
      "full nature vibes",
    ],
    shares: 19,
    src: "pic9.jpg",
    caption: "Golden sands 🏖️",
  },
  {
    id: uuidv4(),
    username: "kiran_rajput",
    likes: 18,
    comments: [
      "what a view!",
      "so much peace here",
      "kitni shandar pic hai!",
      "breathtaking scene",
      "dekh ke achha laga",
      "jo like karega uske sapne pure honge 😂",
      "seriously awesome",
      "superb location",
    ],
    shares: 12,
    src: "pic10.jpg",
    caption: "Mountains and sun ❤️",
  },
  {
    id: uuidv4(),
    username: "deepa_singh",
    likes: 30,
    comments: [
      "ye to kamaal hai!",
      "unbelievable beauty",
      "such a cool pic",
      "this is goals! ❤️",
      "so amazing to see this",
      "aaj tak nahi dekha kuch aisa",
      "perfectly clicked",
      "pure bliss",
    ],
    shares: 22,
    src: "pic11.jpg",
    caption: "Lakeside magic 🌅",
  },
];

module.exports = posts;